name: Publish

on:
  push:
    tags: [ "*" ]

jobs:
  sbt:
    name: sbt publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.6

      - name: Set up JDK 17
        uses: coursier/setup-action@v1.3.9
        with:
          jvm: temurin:1.21

      - name: Publish
        run: |-
          sbt clean test publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}