name: Publish

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    # runs on main repo only
    if: github.repository == 'klubraum/stripe-akka-http'
    name: Release
    environment: release
    runs-on: ubuntu-24.04
    steps:
      - name: Set Timezone to Europe/Berlin
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Berlin"
          timezoneMacos: "Europe/Berlin"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Set up JDK 21
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.21
          apps: sbt

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
          STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
        run: sbt clean test publish